### ISSUE TITLE
Ungraceful end after ^C

### ISSUE THREAD

**Issue by xrat** [rcmdnk/sentaku#8]
```
$ sentaku -v
sentaku v0.4.7 17/Apr/2016
$ echo a b c d | sentaku
[shows sentaku, pressing q]
$ [back at cursor]
```
but
```
$ echo a b c d | sentaku
[shows sentaku, pressing ^C]
sentaku: line 314: 1: command not found
sentaku: line 315: 2: command not found
...
sentaku: line 1311: 998: command not found
sentaku: line 1312: 999: command not found
$ [back at cursor]
```
moreover
```
$ echo a b c d | sentaku
[shows sentaku, pressing / (for search) and ^C]
sentaku: line 314: 1: command not found
...
sentaku: line 1312: 999: command not found
$ [back at cursor, but cursor not shown]
```

**Comment by rcmdnk** [comment]
Thanks for the report.
I found a bug at C-c (IFS was not correctly restored),
and after fixing it, such `command not found` error disappeared.

It is fixed in v0.5.1.

**Comment by xrat** [comment]
Great! Thanks a lot.
However, line echo is still missing (at least for me):
``` bash
$ echo a b c d | sentaku
[pressed ^C]
[at prompt I enter `echo foo`, but it is not shown, only the result]
$ foo
[command `stty echo` helps -- typed but of course not shown]
$ $ echo foo
foo
$
```
I haven't had a chance to look at the code myself. In one of my own Bash scripts I found that I needed `stty echo`, also found no other way to restore the terminal's "echo" setting.
I hope that helps.

**Comment by rcmdnk** [comment]
ok, it is a bit complex and I'm still not fully sure,
but I found that there are different behaviors in GNU and BSD (mac).

In Mac, it worked well, but I got same problem at Linux.

I put a patch and it could solve the problem at Linux.
I think this patch doesn't make anything worse, but please let me know if you find anything wrong.

It is fixed in v0.5.3.

**Comment by xrat** [comment]
I am sorry these things always get more complicated than one would hope. It works on the command line but my scripts don't work. Here's a minimal example:
``` bash
$ cat tmp.sh 
#!/bin/bash
result=$(echo a b | _SENTAKU_NOHEADER=1 sentaku)
echo result=$result
$ ./tmp.sh # typing ^C in sentaku
stty: standard input: Input/output error
stty: standard input: Input/output error
```
I did some research, but again could not find a solution :/

**Comment by rcmdnk** [comment]
hmm... so there are more cases than what I thought...

Though I could not find how to identify this case,
this is just an error output then I put them in /dev/null.
I think it is ok for practical purposes.

v0.5.4.

**Comment by xrat** [comment]
Absolutely! Thanks a lot!
